### PR TITLE
Added crystallographic orbits

### PR DESCRIPTION
**Pull request by lauri-codes**
Added the crystallographic orbits to the dataset as discussed in issue #90. Should be a relative straightforward as only new functionality is added and the old is unaffected. Feel free to modify as you see fit.

### CODE REVIEW

**Comment by atztogo** [comment]
I thought what you want is the symmetrically equivalent atoms in the input crystal without considering symmetry breaking by the input lattice. But as far as I read your PR, what you want is the symmetrically equivalent atoms in standardized crystal structure. Am I correct? Then now I see your naming `std_equivalent_atoms` is probably better than `crystallographic_orbits`.

**Comment by atztogo** [comment]
`wyckoffs` are given for the atoms of the input crystal structure but not the standardized crystal structure. So I thought as I wrote above.

**Comment by lauri-codes** [comment]
Yes, I want the symmetrically equivalent atoms in the standardized cell, sorry if this was unclear. Should I change the names to std_equivalent_atoms?

**Comment by atztogo** [comment]
I'm glad that we can communicate using code.

I see. Then we should have `std_wyckoffs`, too. We can add three new members, `std_wyckoffs`, `std_crystallographic_orbits`, and `crystallographic_orbits` during v1.x. I will merge and modify your code to the develop branch.

**Comment by lauri-codes** [comment]
Ok, perfect!

**Comment by atztogo** [comment]
I spent some time to think about how it should be done. I merged your PR and now `crystallographic_orbits` is accessible, but not by your definition. I implemented as I misunderstood about it. The length of `crystallographic_orbits` is the number of atoms in the input crystal structure, but not the standardized unit cell. In your example, these are the same number though. I chose this definition because I don't want to increase the specification if possible to avoid increasing maintenance cost. 

`crystallographic_orbits` and `equivalent_atoms` in standardized unit cell must be the same, and they can be obtained via `mapping_to_primitive`, `std_mapping_to_primitive`, and `crystallographic_orbits` in principle. So with a little more code, you can get those information. But it requires like 10 lines in python code. So I am wondering how I can provide these information currently.

**Comment by atztogo** [comment]
The following is the python code to obtain `std_crystallographic_orbits`. This code can be much simple if I am clever.

```python
    equiv_atoms_to_primitive = {i: j for i, j in zip(
        symmetry_dataset['mapping_to_primitive'][::-1],
        symmetry_dataset['crystallographic_orbits'][::-1])}
    equiv_atoms_prim = [equiv_atoms_to_primitive[i]
                        for i in range(len(equiv_atoms_to_primitive))]
    equiv_atoms_std = [equiv_atoms_prim[i]
                       for i in symmetry_dataset['std_mapping_to_primitive']]
    std_crystallographic_orbits = {}  # atom indices are those in input cell
    for i, j in enumerate(equiv_atoms_std):
        if j not in std_crystallographic_orbits:
            std_crystallographic_orbits[j] = i
    # atom indices are mapped to those in the standardized cell.
    std_crystallographic_orbits = [std_crystallographic_orbits[i]
                                   for i in equiv_atoms_std]
```

**Comment by atztogo** [comment]
@lauri-codes , is this OK for you?

**Comment by lauri-codes** [comment]
Hi @atztogo,
This is perfectly fine. Thanks a lot!

**Comment by atztogo** [comment]
OK. I will release soon a new version including this PR. Thanks for your PR. I will close this PR.

**Pull request closed without merging**
