### PR TITLE
cmake: use CMAKE_INSTALL_PREFIX

### PR DESCRIPTION
**Pull request by davydden**

### CODE REVIEW

**Comment by atztogo** [comment]
I'm not good at cmake. Could you explain the difference for me?

**Comment by davydden** [comment]
> Could you explain the difference for me?

well, you never install libraries into the source you are building from. You install them into `CMAKE_INSTALL_PREFIX`, see https://cmake.org/cmake/help/v3.0/variable/CMAKE_INSTALL_PREFIX.html

**Comment by davydden** [comment]
also, `cmake` is out-of-source build, so I can build several versions from the same source and `cmake` script shall not pollute sources anyhow.

**Comment by atztogo** [comment]
I see. Thanks.

**Pull request merged**
