### PR TITLE
Fix python tests

### PR DESCRIPTION
**Pull request by merkys**
Testing in Python is usually done via ``python setup.py test``. To enable this for spglib, the test suite has to be defined in setup.py and filesystem paths in tests have to be made relative to setup.py location. This PR contains both fixes. On my machine (Ubuntu 16) all tests for both Python2 and Python3 pass now via ``python{,3} setup.py test``.

### CODE REVIEW

**Comment by atztogo** [comment]
This affects to travis on my repository, but also maybe conda-forge. @jochym , how do you think?

**Comment by atztogo** [comment]
Does this need to install nose explicitly? I ran your pull request on travis and nose was installed automatically in running test.

**Comment by merkys** [comment]
The test-dependency on ``nose`` is specified in setup.py via ``tests_require=['nose']``. I assume that on issuing ``python setup.py test`` these requirements are installed automatically.

**Comment by atztogo** [comment]
Thanks. I merged your commits to the develop branch. I may soon merge it to the master branch ( @jochym, is this fine?)

**Comment by merkys** [comment]
Great, thanks!

**Pull request merged**
